export class ConcreteBon {
  bonId!: string | null;
  concreteCustomer_id!: string | null;
  concreteCustomer_name: string = '';
  customerProject: string = '';
  bonManualNum: string = '';
  concreteId!: string | null;
  concreteName: string = '';
  concreteQty: number = 0;
  driverName: string = '';
  truckId!: string | null;
  truckName: string = '';
  metrPrice: number = 0;
  date: string = '';
  time: string = '';
  pump: string = '';
  madeBy: string = '';
  notes: string = '';
  concreteReceipt_id: string = '0';
}
